# @autor: Juliana Yepes Arias
# @Fecha: 12/03/2025
# @Descripcion: Programa que imprime caracteristicas importantes de python

# Formato de salida
# Primera forma: print()
mi_nombre = "Juliana Yepes Arias"
print("hola mundo", mi_nombre)

# Segunda forma: print() con el concatenador +
print("hola mundo " + mi_nombre)

ficha = 2959811
print("Hola ", mi_nombre, " ficha", str(ficha))

# Tercera forma: print(f"")
print(f"Hola {mi_nombre}, ficha: {ficha}")
